### ISSUE TITLE
It seems spacy do not support Chinese now.

### ISSUE THREAD

**Issue by guotong1988** [crownpku/Awesome-Chinese-NLP#5]
@crownpku 
Thank you.
https://spacy.io

**Comment by crownpku** [comment]
No, spacy doesn't support Chinese for now. I see there are trials on building Chinese model for spacy like [here](https://github.com/howl-anderson/Chinese_models_for_SpaCy)

**Comment by yzj19870824** [comment]
@crownpku That's only suitable for SpaCy Version 2.0
